import { readdirSync, writeFileSync, existsSync } from "node:fs";
import { join, extname, basename } from "node:path";

const dir = join(process.cwd(), "public", "icons");
const files = existsSync(dir)
  ? readdirSync(dir).filter((f) => [".svg", ".png"].includes(extname(f).toLowerCase()))
  : [];
const map = {};
for (const f of files) {
  const key = basename(f, extname(f)).normalize("NFC");
  // svg wins over png when both exist
  if (!map[key] || extname(f).toLowerCase() === ".svg") map[key] = `/icons/${encodeURIComponent(f)}`;
}
writeFileSync(
  join(process.cwd(), "src", "lib", "custom-icons.generated.ts"),
  `// Generated by scripts/gen-icons.mjs from public/icons — do not edit.\nexport const CUSTOM_ICONS: Record<string, string> = ${JSON.stringify(map, null, 2)};\n`,
);
console.log(`custom icons: ${files.length}`);
